apiVersion: v2
name: notification-service
description: Railway Timetable Distribution Platform — Notification Service
type: application
version: 1.0.0
appVersion: "1.0.0-SNAPSHOT"
keywords:
  - railway
  - notification
  - spring-boot
home: https://github.com/tech-adivas/raildisttt
